### ISSUE TITLE
Having Issue Building CRD (Gradle)

### ISSUE THREAD

**Issue by KMCGit** [HL7-DaVinci/CRD#287]
I am attempting to follow the documentation and build the project. I am receiving a successful build, but the website/server is not launching. 

After following the instructions (and making sure to have the same versions) running "gradle bootRun" from drlsroot/CRD, and I am receiving the following:

***************************
APPLICATION FAILED TO START
***************************

Description:

Field fileStore in org.hl7.davinci.endpoint.Application required a bean of type 'org.hl7.davinci.endpoint.files.FileStore' that could not be found.

The injection point has the following annotations:
        - @org.springframework.beans.factory.annotation.Autowired(required=true)

Action:

Consider defining a bean of type 'org.hl7.davinci.endpoint.files.FileStore' in your configuration.

BUILD SUCCESSFUL in 4s
8 actionable tasks: 1 executed, 7 up-to-date

***************************

(How could I remedy this? Any advice to successfully build is greatly appreciated. Thanks.)

**Comment by bstewartlg** [comment]
This is probably due to a configuration issue around loading resources from the CDS-Library repo:  https://github.com/HL7-DaVinci/CRD/blob/master/SetupGuideForMacOS.md#crd-configs

Ensure that `localDb` is selected as the active Spring profile in the application.yml and that it isn't being overridden in your local environment.

You could also try forcing the profile from the command line with `gradle bootRun --args='--spring.profiles.active=localDb'`

Closing this issue as stale since it is over a year old.  Feel free to reopen if still an issue.
